RuggeroVisintin/SparkEngineWeb

.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

Introduce Conventioanl Commit linter

ci(commitlint): add conventional commit linter

---

.eslintrc.json
package-lock.json
package.json

chore(eslint): add eslint

---

package-lock.json
package.json
test/performance/__mocks__/canvas.ts
test/performance/bench.perf.ts
test/performance/hierarchy.perf.ts
test/performance/physx.perf.ts
test/performance/renderer.perf.ts
test/performance/tsconfig.json

test: add benchmark setup to conduct performance testing

---

examples/simplePongGame/index.html
src/core/types.ts
src/ecs/components/SoundComponent.ts
src/ecs/components/index.ts
src/ecs/systems/SountSystem.ts
src/ecs/systems/index.ts
src/game/GameEngine.ts
test/unit/__mocks__/Audio.ts
test/unit/__mocks__/index.ts
test/unit/ecs/components/SoundComponent.test.ts
test/unit/ecs/systems/SoundSystem.test.ts
test/unit/platform/sfx/SoundLoader.test.ts

feat(ecs): add sounds to entity components systems [#53]

---

src/ecs/components/TransformComponent.ts
test/unit/ecs/components/TransformComponent.test.ts

feat(ecs): add TransformComponentProps to init the component

---

src/ecs/components/BoundingBoxComponent.ts
test/unit/ecs/components/BoundingBoxComponent.test.ts

feat(ecs): add BoundingBoxComponentProps to construct boundingBox from config

---

src/ecs/components/MaterialComponent.ts
test/unit/ecs/components/MaterialComponent.test.ts

feat(ecs): add MaterialComponentProps to quickly initialize the component

---

src/ecs/components/ShapeComponent.ts
test/unit/ecs/components/ShapeComponent.test.ts

feat(ecs): add ShapeComponentProps to quickly initialize the component

---

examples/simplePongGame/index.html
src/ecs/components/SoundComponent.ts
test/unit/ecs/components/SoundComponent.test.ts
test/unit/ecs/systems/SoundSystem.test.ts
test/unit/game/Scene.test.ts

Resolves #115
BREAKING CHANGE: SoundComponentProps is required to create a new SoundComponent

feat(ecs)!: add SoundComponentProps to quickly initialize the component

---

src/ecs/entities/BaseEntity.ts
src/ecs/entities/GameObject.ts
src/ecs/entities/StaticObject.ts
src/ecs/entities/TriggerEntity.ts

feat(ecs): add entities type metadata

---

src/core/decorators/incrementallyUniqueDecorator.ts
src/core/decorators/index.ts
src/ecs/entities/BaseEntity.ts
src/ecs/entities/IEntity.ts
test/unit/ecs/entities/BaseEntity.test.ts

feat(ecs): add default entity name with automatic incremental uniqueness

---

src/engine/GameEngine.ts

fix(engine): fix stuttering due to incorrect framepacing

---

src/core/decorators/incrementallyUniqueDecorator.ts
src/ecs/entities/BaseEntity.ts
src/ecs/entities/GameObject.ts
src/ecs/entities/StaticObject.ts
src/engine/GameEngine.ts
src/engine/Scene.ts
src/platform/inputs/KeyboardDevice.ts
test/unit/__mocks__/assets/EntitiesWithComponents.scene.json
test/unit/ecs/entities/BaseEntity.test.ts
test/unit/game/Scene.test.ts

feat(ecs)!: implement entity unique name setter and getter

---

examples/simplePongGame/index.html
src/physx/Physx.ts
test/unit/physx/Physx.test.ts

feat(physx): add post simulation position on container collision

---

src/engine/GameEngine.ts

feat(engine): add physics cycles configuration

---

src/ecs/components/BoundingBoxComponent.ts
src/ecs/components/RigidBodyComponent.ts

feat(ecs): add RigidBodyComponent

---

.github/workflows/ci.yml

ci: publish dist folder with production build

---

src/ecs/entities/BaseEntity.ts
src/ecs/entities/IEntity.ts
src/ecs/systems/BaseSystem.ts
src/ecs/systems/ISystem.ts
src/ecs/systems/RenderSystem.ts
src/engine/Scene.ts
test/unit/ecs/systems/BaseSystem.test.ts
test/unit/ecs/systems/HierarchySystem.test.ts
test/unit/ecs/systems/InputSystem.test.ts
test/unit/ecs/systems/PhysicsSystemt.test.ts
test/unit/ecs/systems/RenderSystem.test.ts
test/unit/ecs/systems/SoundSystem.test.ts
test/unit/game/Scene.test.ts

feat(scene): add unregisterEntity to remove an entity from a scene

---

examples/simpleRect/index.html
src/platform/gfx/CanvasDevice.ts
src/renderer/Renderer.ts
src/renderer/commands/DrawPrimitiveCommand.ts

feat(renderer): add support to wireframe thickness

---

src/core/decorators/incrementallyUniqueDecorator.ts
src/ecs/entities/BaseEntity.ts
src/engine/Scene.ts
test/unit/ecs/entities/BaseEntity.test.ts
test/unit/game/Scene.test.ts

feat(ecs): change entity's name uniqueness logic to apply only within the scope of the parent scene

---

src/ecs/systems/AnimationSystem.ts
src/ecs/systems/BaseSystem.ts
src/ecs/systems/HierarchySystem.ts
src/ecs/systems/ISystem.ts
src/ecs/systems/InputSystem.ts
src/ecs/systems/PhysicsSystem.ts
src/ecs/systems/RenderSystem.ts
src/ecs/systems/SoundSystem.ts
test/unit/ecs/systems/BaseSystem.test.ts

feat(ecs): add the ability to pause/resume any given system

---

src/core/decorators/typeDecorator.ts
src/ecs/components/ BaseDrawableComponent.ts
src/ecs/components/AnimationComponent.ts
src/ecs/components/BaseComponent.ts
src/ecs/components/BoundingBoxComponent.ts
src/ecs/components/InputComponent.ts
src/ecs/components/MaterialComponent.ts
src/ecs/components/RigidBodyComponent.ts
src/ecs/components/ShapeComponent.ts
src/ecs/components/SoundComponent.ts
src/ecs/components/TransformComponent.ts
src/ecs/components/interfaces/IComponent.ts
src/ecs/entities/BaseEntity.ts
src/ecs/entities/IEntity.ts
test/unit/ecs/components/AnimationComponent.test.ts
test/unit/ecs/components/BoundingBoxComponent.test.ts
test/unit/ecs/components/CameraComponent.test.ts
test/unit/ecs/components/InputComponent.test.ts
test/unit/ecs/components/MaterialComponent.test.ts
test/unit/ecs/components/RigidBodyComponent.test.ts
test/unit/ecs/components/ShapeComponent.test.ts
test/unit/ecs/components/SoundComponent.test.ts
test/unit/ecs/components/TransformComponent.test.ts
test/unit/ecs/entities/BaseEntity.test.ts

feat(ecs): add .toJson() method to get json representation of any component

---

.adr-dir
.github/workflows/ci.yml
.gitignore
docs/architecture/decisions/0001-record-architecture-decisions.md
docs/architecture/decisions/0002-use-unique-names-to-identify-entities.md
examples/sceneLoad/index.html
scripts/build-docs.sh
src/core/decorators/incrementallyUniqueDecorator.ts
src/core/decorators/typeDecorator.ts
src/ecs/entities/BaseEntity.ts
src/ecs/entities/GameObject.ts
src/ecs/entities/StaticObject.ts
src/ecs/entities/TriggerEntity.ts
src/engine/Scene.ts
test/unit/ecs/entities/BaseEntity.test.ts
test/unit/engine/Scene.test.ts
typedoc.json

This is only a POC and it is not meant to be the final solution just yet

chore: add POC code

---

examples/animations/index.html
src/ecs/components/ BaseDrawableComponent.ts
src/ecs/components/ShapeComponent.ts
src/ecs/components/interfaces/IDrawableComponent.ts
src/ecs/systems/RenderSystem.ts
src/engine/GameEngine.ts
test/unit/ecs/components/ShapeComponent.test.ts
test/unit/ecs/systems/RenderSystem.test.ts
test/unit/engine/Scene.test.ts
test/unit/utils.ts

BREAKING CHANGES
* IDrawableComponent.draw() requires additional imageLoader argument
* RenderSystem.constructor() requires additional imageLoader argument

feat(renderer)!: add texture loading when ShapeComponent material draw

---

src/engine/GameEngine.ts
src/engine/Scene.ts
test/unit/engine/GameEngine.test.ts
test/unit/engine/Scene.test.ts

feat(engine): add ability to control when scene should be drawn/hidden

---

src/ecs/components/AnimationComponent.ts
src/ecs/components/MaterialComponent.ts
src/platform/gfx/DOMImageLoader.ts
src/platform/gfx/ImageLoader.ts
test/unit/platform/gfx/ImageLoader.test.ts

feat(ecs): use ImageLoader interface for DOMImageLoader

---

src/ecs/systems/RenderSystem.ts
src/engine/GameEngine.ts
src/engine/Scene.ts
src/renderer/Renderer.ts
test/performance/renderer.perf.ts
test/unit/__mocks__/FakeSystemClock.ts
test/unit/engine/GameEngine.test.ts
test/unit/engine/Scene.test.ts
test/unit/renderer/Renderer.test.ts

feat(engine): add support to multiple RenderSystem(s)

---

src/core/SerializableCallback.ts
src/core/index.ts
src/ecs/components/BoundingBoxComponent.ts
src/ecs/components/interfaces/ICollidableComponent.ts
src/ecs/entities/TriggerEntity.ts
test/unit/ecs/components/BoundingBoxComponent.test.ts
test/unit/ecs/entities/StaticObject.test.ts
test/unit/ecs/entities/TriggerEntity.test.ts

feat(ecs)!: add SerializableCallback to preserve serialized source code when needed

---

.github/workflows/visual-tests-only.yml
examples/cameraMovement/index.html
src/ecs/components/CameraComponent.ts
src/ecs/components/TransformComponent.ts
src/renderer/commands/SetTransformMatrixCommand.ts
test/unit/__mocks__/assets/EntitiesWithComponents.scene.json
test/unit/ecs/components/CameraComponent.test.ts
test/unit/ecs/components/TransformComponent.test.ts
test/unit/engine/Scene.test.ts
test/unit/engine/__snapshots__/Scene.test.ts.snap

feat(ecs): add camera zoom in/out

---

examples/cameraMovement/index.html
src/ecs/components/CameraComponent.ts
test/unit/ecs/components/CameraComponent.test.ts
test/visual/canvasDevice.spec.ts

fix(ecs): fix camera scaling factor
